# Generated by Django 5.0.7 on 2024-07-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_book_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='buy_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
